BioPV/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^$', RedirectView.as_view(url='/homepage/', permanent=True)),
    url(r'^homepage/', include('homepage.urls', namespace='homepage')),
    url(r'^ratings/', include('ratings.urls', namespace='ratings')),
]

homepage/urls.py
from django.conf.urls import patterns, include, url
from . import views

app_name = 'homepage'


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contact_us', views.contact_us, name='contact_us'),
    url(r'^about_us', views.about_us, name='about_us'),
    url(r'^our_team', views.our_team, name='our_team'),
]

ratings/urls.py
from django.conf.urls import patterns, include, url
from . import views

app_name = 'ratings'

urlpatterns = [
    url(r'^$', views.ratings_search, name='ratings_search'),
    url(r'^compare', views.ratings_compare, name='ratings_compare'),
    url(r'^reporting', views.ratings_reporting, name='ratings_reporting'),
    url(r'^add_module', views.ratings_add_module, name='ratings_add_module'),
    url(r'^insert_data', views.insert_data, name='insert_data'),
    url(r'^upload_xml', views.upload_xml, name='upload_xml'),
    url(r'^upload_csv', views.upload_csv, name='upload_csv'),
]

users/urls.py
from django.conf.urls import patterns, include, url
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^register', views.register, name='register'),
    url(r'^profile', views.profile, name='profile'),
]

certification/models.py
from django.db import models

# Create your models here.

homepage/models.py
from django.db import models

# Create your models here.

performance/models.py
from django.db import models

# Create your models here.

ratings/models.py
from django.db import models


class Module(models.Model):
    ModelName = models.CharField(max_length=500, null=False, unique=True)
    ModelDescription = models.CharField(max_length=2000, null=False)
    ManufactureID = models.IntegerField(null=True)
    ModuleManufactureDate = models.DateField(null=True, blank=True)
    ModuleLengthWidth = models.DecimalField(max_digits=5, decimal_places=2, null=False)
    ModuleWeight = models.DecimalField(max_digits=5, decimal_places=2, null=False)
    IndividualCellArea = models.DecimalField(max_digits=5, decimal_places=2, null=False)
    CellTechnology = models.CharField(max_length=500, null=False)
    CellManufacturer = models.CharField(max_length=500, null=False)
    PartNumber = models.CharField(max_length=500, null=False)
    CellManufacturingLocation = models.CharField(max_length=500, null=False)
    TotalNumberOfCells = models.IntegerField()
    NumberOfCellsInParallel = models.IntegerField()
    NumberOfCellsInSeries = models.IntegerField()
    ByPassDiodes = models.IntegerField()
    ByPassDiodeRating = models.DecimalField(max_digits=5, decimal_places=2, null=False)
    ByPassDiodeMaxTemp = models.DecimalField(max_digits=5, decimal_places=2, null=False)
    SeriesFuseRating = models.DecimalField(max_digits=5, decimal_places=2, null=False)
    InterconnectMaterial = models.CharField(max_length=500, null=False)
    SupplierModelNumber = models.CharField(max_length=500, null=False)
    SuperstrateType = models.CharField(max_length=500, null=False)
    SuperstratePartNumber = models.CharField(max_length=500, null=False)
    SuperstrateManufacturer = models.CharField(max_length=500, null=False)
    SubstrateType = models.CharField(max_length=500, null=False)
    SubstratePartNumber = models.CharField(max_length=500, null=False)
    SubstrateManufacturer = models.CharField(max_length=500, null=False)
    FrameType = models.CharField(max_length=500, null=False)
    FrameAdhesive = models.CharField(max_length=500, null=False)
    EncapsulantType = models.CharField(max_length=500, null=False)
    EncapsulantManufacturer = models.CharField(max_length=500, null=False)
    EncapsulantPartNumber = models.CharField(max_length=500, null=False)
    JunctionBoxType = models.CharField(max_length=500, null=False)
    JunctionBoxManufacturer = models.CharField(max_length=500, null=False)
    JunctionBoxPartNumber = models.CharField(max_length=500, null=False)
    JunctionBoxPottingMaterial = models.CharField(max_length=500, null=False)
    JunctionBoxAdhesive = models.CharField(max_length=500, null=False)
    CableType = models.CharField(max_length=500, null=False)
    ConnectorType = models.CharField(max_length=500, null=False)
    MaxSysVoltage = models.DecimalField(max_digits=5, decimal_places=2, null=False)

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'signUpLabel'
            })

certification/views.py
from django.shortcuts import render

# Create your views here.

homepage/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'homepage/index.html')


def contact_us(request):
    return render(request, 'homepage/contact_us.html', {})


def about_us(request):
    return render(request, 'homepage/about_us.html', {})


def our_team(request):
    return render(request, 'homepage/our_team.html', {})

performance/views.py
from django.shortcuts import render

# Create your views here.

ratings/views.py
from django.shortcuts import render
import xml.etree.ElementTree as ET
# from lxml import etree
import csv, io


def ratings_search(request):
    return render(request, 'ratings/ratings_search.html')


def ratings_compare(request):
    return render(request, 'ratings/ratings_compare.html')


def ratings_reporting(request):
    return render(request, 'ratings/ratings_reporting.html')


def ratings_add_module(request):
    return render(request, 'ratings/ratings_add_module.html')


def insert_data(request):
    return render(request, 'ratings/ratings_add_module.html', {'message': 'Information saved successfully'})


def upload_xml(request):
    xmlfile = request.FILES['xml_file']
    tree = ET.parse(xmlfile)
    root = tree.getroot()
    for child in root:
        print(child.tag, child.attrib)
    return render(request, 'ratings/ratings_add_module.html', {'message': 'XML file uploaded successfully'})


def upload_csv(request):
    csv_file = request.FILES['csv_file']
    decoded_file = csv_file.read().decode('utf-8')
    io_string = io.StringIO(decoded_file)
    for line in csv.reader(io_string, delimiter=';', quotechar='|'):
        print(line)
    return render(request, 'ratings/ratings_add_module.html', {'message': 'CSV file uploaded successfully'})

users/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import SignUpForm


def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return render(request, 'registration/login.html', {'message': 'Registration completed successfully. You can sign in now.'})
    else:
        form = SignUpForm()
    return render(request, 'users/create_user.html', {'form': form})


@login_required
def profile(request):
    return render(request, 'users/profile.html')

homepage/templates/homepage/about_us.html
{% extends "homepage/main_template.html" %}
{% load staticfiles %}
{% block title %}
    About Us
{% endblock %}

{% block content %}

    <ol class="breadcrumb">
        <li><a href="{% url 'homepage:index' %}">Home</a></li>
        <li>About Us</li>
    </ol>


    <!-- ======== @Region: #content ======== -->
    <div id="content">
        <div class="container" id="about">
            <div class="row">
                <!--main content-->
                <div class="col-md-9 col-md-push-3">
                    <div class="page-header">
                        <h1>
                            About Us
                            <small>How it all began</small>
                        </h1>
                    </div>
                    <div class="block block-border-bottom-grey block-pd-sm">
                        <h3 class="block-title">
                            What Makes Us Tick!
                        </h3>
                        <img src="{% static 'homepage/img/misc/about-us.png' %}" alt="About us" class="img-responsive img-thumbnail pull-right m-l m-b">
                        <p>This is how it started</p>
                        <p>Elit pellentesque dolor facilisis aenean eu tempor, phasellus lundium risus dolor, augue, ridiculus nascetur odio ridiculus? Hac ac, adipiscing ut dapibus.</p>
                    </div>
                    <div class="block-highlight block-pd-h block-pd-sm">
                        <h3 class="block-title">
                            Our Mission
                        </h3>
                        <p class="text-fancy">Vel in amet mauris? Turpis pulvinar a proin tincidunt pid, vel odio lundium sit, cras. Duis mattis porttitor nunc elementum eros, in turpis nec. Lectus dictumst risus ut ac porta, urna ac vel, a ut dis!</p>
                    </div>
                    <div class="block">
                        <h3 class="block-title">
                            Vital Stats
                        </h3>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="stat">
                                    <span data-counter-up>1000</span>s
                                    <small>Happpy Customers</small>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="stat">
                                    <span data-counter-up>163</span>+
                                    <small>GB Transfered</small>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="stat">
                                    <span data-counter-up>214</span>
                                    <small>Bugs Fixed</small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- sidebar -->
                {% include 'homepage/sidebar.html' with active_menu=1 %}
            </div>
        </div>
    </div>

{% endblock %}

homepage/templates/homepage/contact_us.html
 {% extends "homepage/main_template.html" %}
{% load staticfiles %}
{% block title %}
    Contact Us
{% endblock %}

{% block content %}

    <ol class="breadcrumb">
        <li><a href="{% url 'homepage:index' %}">Home</a></li>
        <li>Contact Us</li>
    </ol>

    <!-- ======== @Region: #content ======== -->
    <div id="content">
        <div class="container" id="about">
            <div class="row">
                <!--main content-->
                <div class="col-md-9 col-md-push-3">
                    <div class="page-header">
                        <h1>
                            Contact Us
                            <small>How to get in touch</small>
                        </h1>
                    </div>
                    <div class="block block-border-bottom-grey block-pd-sm">

                            <div class="row text-center">

                                <div class="col-sm-4 col-xs-6">
                                    <h1><span class="glyphicon glyphicon-earphone"></span></h1>
                                    <h3>Phone</h3>
                                    <p><a href="tel:14807271220">+1 (480) 727-1220</a></p>
                                </div>

                                <div class="col-sm-4 col-xs-6">
                                    <h1><span class="glyphicon glyphicon-map-marker"></span></h1>
                                    <h3>Address</h3>
                                    <p>7349 Innovation Way S,<br>
                                        Mesa, AZ 85212.</p>
                                </div>

                                <div class="col-sm-4 col-xs-6">
                                    <h1><span class="glyphicon glyphicon-send"></span></h1>
                                    <h3>E-mail</h3>
                                    <p><a href="mailto:kuitche@asu.edu?Subject=Hello%20" target="_top">kuitche@asu.edu</a></p>
                                </div>

                            </div>
                            <br>
                            <div class="row text-center">
                                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d13338.222552013178!2d-111.6741693!3d33.3042864!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x73f9fb94f99af148!2sPhotovoltaic+Reliability+Laboratory!5e0!3m2!1sen!2sus!4v1498702047024"
                                        width="80%" height="400px" frameborder="0" style="border:0" allowfullscreen></iframe>
                            </div>

                        </div>
                </div>
                <!-- sidebar -->
                {% include 'homepage/sidebar.html' with active_menu=3 %}
            </div>
        </div>
    </div>

{% endblock %}

homepage/templates/homepage/our_team.html
{% extends "homepage/main_template.html" %}
{% load staticfiles %}
{% block title %}
    Our Team
{% endblock %}

{% block content %}

    <ol class="breadcrumb">
        <li><a href="{% url 'homepage:index' %}">Home</a></li>
        <li>Our Team</li>
    </ol>


    <!-- ======== @Region: #content ======== -->
    <div id="content">
        <div class="container" id="about">
            <div class="row">
                <!--main content-->
                <div class="col-md-9 col-md-push-3">
                    <div class="page-header">
                        <h1>
                            Our Team
                            <small>Our team of stars</small>
                        </h1>
                    </div>
                    <div class="block block-border-bottom-grey block-pd-sm">
                     <div class="row text-center">

                                <div class="col-sm-4 col-xs-6">
                                    <h1><span class="glyphicon glyphicon-user"></span></h1>
                                    <h3>Dr. Joseph Kuitche</h3>
                                    <p><a href="mailto:kuitche@asu.edu?Subject=Hello%20" target="_top">kuitche@asu.edu</a></p>
                                </div>

                                <div class="col-sm-4 col-xs-6">
                                    <h1><span class="glyphicon glyphicon-user"></span></h1>
                                    <h3>Abhishek Zambre</h3>
                                    <p><a href="mailto:kuitche@asu.edu?Subject=Hello%20Abhishek" target="_top">azambre@asu.edu</a></p>
                                </div>

                                <div class="col-sm-4 col-xs-6">
                                    <h1><span class="glyphicon glyphicon-user"></span></h1>
                                    <h3>Apoorva Telukuntla</h3>
                                    <p><a href="mailto:kuitche@asu.edu?Subject=Hello%20" target="_top">atelukun@asu.edu@asu.edu</a></p>
                                </div>

                            </div>
                    </div>
                </div>
                <!-- sidebar -->
                {% include 'homepage/sidebar.html' with active_menu=2 %}
            </div>
        </div>
    </div>


{% endblock %}

homepage/templates/homepage/sidebar.html
<div class="col-md-3 col-md-pull-9 sidebar visible-md-block visible-lg-block">
    <ul class="nav nav-pills nav-stacked">
        <li {% if active_menu == 1 %} class="active" {% endif %}>
            <a href="{% url 'homepage:about_us' %}" class="first">
                About Us
                <small>How It All Began</small>
            </a>
        </li>
        <li {% if active_menu == 2 %} class="active" {% endif %}>
            <a href="{% url 'homepage:our_team' %}">
                Our Team
                <small>Our team of stars</small>
            </a>
        </li>
        <li {% if active_menu == 3 %} class="active" {% endif %}>
            <a href="{% url 'homepage:contact_us' %}">
                Contact Us
                <small>How to get in touch</small>
            </a>
        </li>
    </ul>
</div>

ratings/templates/ratings/ratings_compare.html
{% extends "homepage/main_template.html" %}

{% block title %}
    PV Ratings - Compare Ratings
{% endblock %}

{% block content %}

    <ol class="breadcrumb">
        <li><a href="{% url 'homepage:index' %}">Home</a></li>
        <li>PV Ratings</li>
        <li>Compare Ratings</li>
    </ol>


    <!-- ======== @Region: #content ======== -->
    <div id="content">
        <div class="container" id="about">
            <div class="row">
                <!--main content-->
                <div class="col-md-9 col-md-push-3">

                    <!-- Add Content Here... -->
                    <div class="page-header">
                        <h2>
                            Compare Ratings
                            <small>Compare ratings for STC, NOTC and LowE testings</small>
                        </h2>
                    </div>
                    <div class="block block-border-bottom-grey block-pd-sm">

                        <label for="module-name">Select Module Type </label>
                        <select id="module-name" name="value" class="form-control">
                            <option value="1">Select</option>
                            <option value="2">Type 1</option>
                            <option value="2">Type 2</option>
                            <option value="2">Type 3</option>
                            <option value="2">Type 4</option>
                            <option value="2">Type 5</option>
                            <option value="2">Type 6</option>
                        </select>

                        <label for="module-name">Select Module 1 </label>
                        <select id="module-name" name="module1" class="form-control">
                            <option value="1">Select</option>
                            <option value="2">Module Example 1</option>
                            <option value="2">Module Example 2</option>
                            <option value="2">Module Example 3</option>
                            <option value="2">Module Example 4</option>
                            <option value="2">Module Example 5</option>
                            <option value="2">Module Example 6</option>
                        </select>

                        <label for="module-name">Select Module 2 </label>
                        <select id="module-name" name="module2" class="form-control">
                            <option value="1">Select</option>
                            <option value="2">Module Example 1</option>
                            <option value="2">Module Example 2</option>
                            <option value="2">Module Example 3</option>
                            <option value="2">Module Example 4</option>
                            <option value="2">Module Example 5</option>
                            <option value="2">Module Example 6</option>
                        </select>

                        <label for="module-name">Select Module 3 </label>
                        <select id="module-name" name="module3" class="form-control">
                            <option value="1">Select</option>
                            <option value="2">Module Example 1</option>
                            <option value="2">Module Example 2</option>
                            <option value="2">Module Example 3</option>
                            <option value="2">Module Example 4</option>
                            <option value="2">Module Example 5</option>
                            <option value="2">Module Example 6</option>
                        </select>

                        <label for="module-name">Select Module 4 </label>
                        <select id="module-name" name="module4" class="form-control">
                            <option value="1">Select</option>
                            <option value="2">Module Example 1</option>
                            <option value="2">Module Example 2</option>
                            <option value="2">Module Example 3</option>
                            <option value="2">Module Example 4</option>
                            <option value="2">Module Example 5</option>
                            <option value="2">Module Example 6</option>
                        </select>

                        <label for="module-name">Select Module 5 </label>
                        <select id="module-name" name="module5" class="form-control">
                            <option value="1">Select</option>
                            <option value="2">Module Example 1</option>
                            <option value="2">Module Example 2</option>
                            <option value="2">Module Example 3</option>
                            <option value="2">Module Example 4</option>
                            <option value="2">Module Example 5</option>
                            <option value="2">Module Example 6</option>
                        </select>


                        <label for="test_condition">Select Test Condition:</label>
                        <select id="test_condition" name="test" class="form-control">
                            <option value="1">Select</option>
                            <option value="2">STC</option>
                            <option value="3">LowE</option>
                            <option value="4">NOCT</option>
                        </select>

                        <input type="submit" class="form-control btn btn-success" value="Compare">

                    </div>


                    <!-- Stop Content Here... -->
                </div>
                <!-- sidebar -->
                {% include 'ratings/sidebar.html' with active_menu=2 %}
            </div>
        </div>
    </div>

{% endblock %}

ratings/templates/ratings/ratings_reporting.html
{% extends "homepage/main_template.html" %}

{% block title %}
    PV Ratings - Data Reporting
{% endblock %}

{% block content %}

    <ol class="breadcrumb">
        <li><a href="{% url 'homepage:index' %}">Home</a></li>
        <li>PV Ratings</li>
        <li>Data Reporting</li>
    </ol>


    <!-- ======== @Region: #content ======== -->
    <div id="content">
        <div class="container" id="about">
            <div class="row">
                <!--main content-->
                <div class="col-md-9 col-md-push-3">
                    <div class="page-header">
                        <h2>
                            Data Reporting
                            <small>Report test data</small>
                        </h2>
                    </div>
                    <div class="block block-border-bottom-grey block-pd-sm">

                        <div class="input-group">
                            <input id="tags"  type="text" class="form-control" placeholder="Enter module number here...">
                            <span class="input-group-btn">
                                <button class="btn btn-primary" type="button">Search</button>
                                <button class="btn btn-success" type="button">Advanced Search</button>
                            </span>
                        </div><!-- /input-group -->

                    </div>
                </div>
                <!-- sidebar -->
                {% include 'ratings/sidebar.html' with active_menu=3 %}
            </div>
        </div>
    </div>

{% endblock %}

ratings/templates/ratings/ratings_search.html
{% extends "homepage/main_template.html" %}

{% block title %}
    PV Ratings - Name Plate Search
{% endblock %}

{% block content %}

    <ol class="breadcrumb">
            <li><a href="{% url 'homepage:index' %}">Home</a></li>
            <li>PV Ratings</li>
            <li>Name Plate Search</li>
        </ol>

    <script>
        $( function() {
            var availableTags = [
                "ActionScript",
                "AppleScript",
                "Asp",
                "BASIC",
                "C",
                "C++",
                "Clojure",
                "COBOL",
                "ColdFusion",
                "Erlang",
                "Fortran",
                "Groovy",
                "Haskell",
                "Java",
                "JavaScript",
                "Lisp",
                "Perl",
                "PHP",
                "Python",
                "Ruby",
                "Scala",
                "Scheme"
            ];

            $( "#tags" ).autocomplete({
                source: availableTags
            });
        });

    </script>

{#    <!-- ======== @Region: #content ======== -->#}
{#    <div id="content">#}
{#            <div class="container">#}
{##}
{#                <div class="col-md-3">#}
{#                    <div class="list-group wizard-menu">#}
{#                        <a href="{% url 'ratings:ratings_search' %}" class="list-group-item active step-1-menu" data-for=".step-1">#}
{#                            <h5 class="list-group-item-heading">Name Plate Search</h5>#}
{#                        </a>#}
{#                        <a href="{% url 'ratings:ratings_compare' %}" class="list-group-item step-2-menu" data-for=".step-2">#}
{#                            <h5 class="list-group-item-heading">Compare Ratings</h5>#}
{#                        </a>#}
{#                        <a href="{% url 'ratings:ratings_compare_stc' %}" class="list-group-item step-3-menu" data-for=".step-3">#}
{#                            <h6 class="list-group-item-heading">STC</h6>#}
{#                        </a>#}
{#                        <a href="{% url 'ratings:ratings_compare_notc' %}" class="list-group-item step-4-menu" data-for=".step-4">#}
{#                            <h6 class="list-group-item-heading">NOTC</h6>#}
{#                        </a>#}
{#                        <a href="{% url 'ratings:ratings_compare_lowe' %}" class="list-group-item step-5-menu" data-for=".step-5">#}
{#                            <h6 class="list-group-item-heading">LowE</h6>#}
{#                        </a>#}
{#                        <a href="{% url 'ratings:ratings_reporting' %}" class="list-group-item step-6-menu" data-for=".step-6">#}
{#                            <h5 class="list-group-item-heading">Data Reporting</h5>#}
{#                        </a>#}
{#                        <a href="{% url 'ratings:ratings_add_module' %}" class="list-group-item step-7-menu" data-for=".step-7">#}
{#                            <h5 class="list-group-item-heading">Add Module Type</h5>#}
{#                        </a>#}
{#                    </div>#}
{#                </div>#}
{##}
{#                <div class="col-md-9">#}
{#                    <h3 class="block-title text-weight-strong text-uppercase">#}
{#                        Name Plate Search#}
{#                    </h3>#}
{#                    <hr>#}
{##}
{#                     <div class="input-group">#}
{#                         <input id="tags"  type="text" class="form-control" placeholder="Enter module number here...">#}
{#                         <span class="input-group-btn">#}
{#                             <button class="btn btn-primary" type="button">Search</button>#}
{#                             <button class="btn btn-success" type="button">Advanced Search</button>#}
{#                         </span>#}
{#                     </div><!-- /input-group -->#}
{#                </div>#}
{#            </div>#}
{##}
{#    </div>#}

    <!-- ======== @Region: #content ======== -->
    <div id="content">
        <div class="container" id="about">
            <div class="row">
                <!--main content-->
                <div class="col-md-9 col-md-push-3">
                    <div class="page-header">
                        <h2>
                            Name Plate Search
                            <small>Search from catalog</small>
                        </h2>
                    </div>
                    <div class="block block-border-bottom-grey block-pd-sm">

                        <div class="input-group">
                            <input id="tags"  type="text" class="form-control" placeholder="Enter module number here...">
                            <span class="input-group-btn">
                                <button class="btn btn-primary" type="button">Search</button>
                                <button class="btn btn-success" type="button">Advanced Search</button>
                            </span>
                        </div><!-- /input-group -->

                    </div>
                </div>
                <!-- sidebar -->
                {% include 'ratings/sidebar.html' with active_menu=1 %}
            </div>
        </div>
    </div>


{% endblock %}

ratings/templates/ratings/sidebar.html
<div class="col-md-3 col-md-pull-9 sidebar visible-md-block visible-lg-block">
    <ul class="nav nav-pills nav-stacked">
        <li {% if active_menu == 1 %} class="active" {% endif %}>
            <a href="{% url 'ratings:ratings_search' %}" class="first">
                Name Plate Search
                <small>Search PV componenet</small>
            </a>
        </li>
        <li {% if active_menu == 2 %} class="active" {% endif %}>
            <a href="{% url 'ratings:ratings_compare' %}">
                Compare Ratings
                <small>Comparison across all testings</small>
            </a>
        </li>
        <li {% if active_menu == 3 %} class="active" {% endif %}>
            <a href="{% url 'ratings:ratings_reporting' %}">
                Data Reporting
                <small>Submit testing report</small>
            </a>
        </li>
        <li {% if active_menu == 4 %} class="active" {% endif %}>
            <a href="{% url 'ratings:ratings_add_module' %}">
                Add Module Type
                <small>Add new module</small>
            </a>
        </li>
    </ul>
</div>